# Site settings
title: Project by kokoye2007
description: project description short description
keywords: Ubuntu, RaspberryPi, Arduino, Open Street Map, DevOps
author: kokoye2007
baseurl: "https://kokoye2007.github.com" # the subpath of your site, e.g. /blog/
url: "/project" # the base hostname & protocol for your site
